### ISSUE TITLE
Allow cluster and secret ARN in the connection string

### ISSUE THREAD

**Issue by multimeric** [cloud-utils/sqlalchemy-aurora-data-api#32]
One issue with the API at the moment is that you can't transparently swap from say psycopg postgres to Data API postgres using only environment variables. This is a desirable behaviour because it means that the underlying code is agnostic to the Data API, and will therefore work identically with native Postgres. This API means that I need to add some awareness of the Data API into my actual application.

Although the connection string would be messy, I would like to suggest allowing `postgresql+auroradataapi://{secret_arn}@{cluster_arn}`, which is roughly analogous to
`postgresql+psycopg2://{username}:{password}@{host}:{port}/postgres`.

**Comment by bruceadams** [comment]
This is supported already through parameters on the connection url.

The specific examples I have are for MySQL. These work, without any code changes:

- `SQLALCHEMY_URL=mysql+pymysql://root:root@localhost:3306/${database_name}`
- `SQLALCHEMY_URL=mysql+auroradataapi://:@/${database_name}?aurora_cluster_arn=${cluster_arn}&secret_arn=${secret_arn}"`

Another approach, still no code changes, just environment variables, is to set the environment variables that [aurora_data_api](https://github.com/cloud-utils/aurora-data-api/blob/main/aurora_data_api/__init__.py#L45-L46) will pick up.

- `SQLALCHEMY_URL=mysql+auroradataapi://:@/${database_name}`
- `AURORA_CLUSTER_ARN=${cluster_arn}`
- `AURORA_SECRET_ARN=${secret_arn}`

**Comment by multimeric** [comment]
Oh, this is very neat, not sure how I missed it in the readme. Many thanks!
