### ISSUE TITLE
Should we recommend SQLAlchemy NullPool?

### ISSUE THREAD

**Issue by bruceadams** [cloud-utils/sqlalchemy-aurora-data-api#36]
I wonder if [sqlalchemy-aurora-data-api](https://github.com/cloud-utils/sqlalchemy-aurora-data-api) should recommend using [SQLAlchemy NullPool](https://docs.sqlalchemy.org/en/14/core/pooling.html#sqlalchemy.pool.NullPool)?

As I was figuring out https://github.com/cloud-utils/aurora-data-api/issues/43 I got looking at interactions between [SQLAlchemy pooling](https://docs.sqlalchemy.org/en/14/core/pooling.html), [sqlalchemy-aurora-data-api](https://github.com/cloud-utils/sqlalchemy-aurora-data-api) and [aurora-data-api](https://github.com/cloud-utils/aurora-data-api).

The documentation for [SQLAlchemy NullPool](https://docs.sqlalchemy.org/en/14/core/pooling.html#sqlalchemy.pool.NullPool) says:

> A Pool which does not pool connections.
>
> Instead it literally opens and closes the underlying DB-API connection per each connection open/close.
>
> Reconnect-related functions such as recycle and connection invalidation are not supported by this Pool implementation, since no connections are held persistently.

Since [aurora-data-api](https://github.com/cloud-utils/aurora-data-api) is fundamentally connection-less (part of what makes it great!), having SQLAlchemy make efforts managing _connections_ seems like unneeded effort and, especially in failure situations, potentially confusing.

**Comment by kislyuk** [comment]
Thanks for the pointer, this sounds like a good idea for this package.

**Comment by kislyuk** [comment]
I'm actually not sure what the upside of using NullPool would be. While the overhead of creating a new aurora-data-api client is relatively low, it's not zero. I'd prefer to make aurora-data-api fully threadsafe instead of asking users to introduce more configuration that they may or may not apply.

AFAIK the only non-threadsafe portion of aurora-data-api right now is the transaction id bound to the connection. I think the transaction id will have to be made thread-local.

**Comment by kislyuk** [comment]
Filed https://github.com/cloud-utils/aurora-data-api/issues/47 to keep track of that.

**Comment by bruceadams** [comment]
I don't know of a reason that it's _important_ to use NullPool. I just know that SQLAlchemy is doing work presuming that there is a very expensive TCP connection behind the database connector and that is not the case here. Why have SQLAlchemy doing work is does not need to do? How the SQLAlchemy connection management work balances against the fairly small, but not zero, cost of creating a new sqlalchemy-aurora-data-api instance? I don't know.
