### ISSUE TITLE
Question: Asynchronous I/O (asyncio) compatibility

### ISSUE THREAD

**Issue by mfulgo** [cloud-utils/sqlalchemy-aurora-data-api#39]
I'm wondering about using this plugin with the [asyncio support in SQLAlchemy](https://docs.sqlalchemy.org/en/14/orm/extensions/asyncio.html#asyncio-platform-installation-notes).

Given the `+asyncpg` in the connection strings in all the examples, I'm assuming that there would need to be modifications made to this project to support it, but maybe I'm wrong. It might just be helpful to document [lack of] support for it (if only in this issue).

**Comment by kislyuk** [comment]
Thanks for your interest. Asyncio is not supported in this library, and there are no specific plans to support it.

This library depends on boto3/botocore, which is an officially supported, extremely high quality dependency. Until botocore adds support for asyncio, this library will not be in a position to support it (third-party forks of boto3 that add asyncio are not a suitable substitute).

In general I'm not sure that asyncio has high utility - it would be helpful if people could provide examples of concrete advantages that it brought to their application (in the form of benchmarks of asyncio vs. traditional worker pool architectures).

**Comment by mfulgo** [comment]
Thanks, Andrey!
I think that covers the question, and this issue can serve to answer it for anyone else who's searching for the same thing.
